spring:
  application:
    name: Polaris
  datasource:
    url: jdbc:h2:mem:polaris;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;USER=sa
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:sql/init.sql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    #    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      write_dates_as_timestamps: false
  mvc:
    format:
      date: yyyy-MM-dd
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
debug: true